/*
 * This source file was generated by the Gradle 'init' task
 */
package expense.management.tracker;

import org.junit.jupiter.api.Test;

class ExpenseManagementTrackerAppTest {
    @Test void appHasAGreeting() {
        ExpenseManagementTrackerApp classUnderTest = new ExpenseManagementTrackerApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
