/*
 * This source file was generated by the Gradle 'init' task
 */
package practice.spring.mvc;

import org.junit.jupiter.api.Test;

class PracticeSpringMVCAppTest {
    @Test void appHasAGreeting() {
        PracticeSpringMVCApp classUnderTest = new PracticeSpringMVCApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
