/*
 * This source file was generated by the Gradle 'init' task
 */
package sports.management;

import org.junit.jupiter.api.Test;

class SportsManagementAppTest {
    @Test void appHasAGreeting() {
        SportsManagementApp classUnderTest = new SportsManagementApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
